apiVersion: v1
kind: Service
metadata:
  name: 'openresty-84-test'
  namespace: k8s-openresty-php
spec:
  ports:
  - name: openresty
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: 'k8s-openresty-php-84-test'
  sessionAffinity: None
  type: ClusterIP
