FROM alpine:3.13

ARG PHP_VERSION=8
ARG ATATUS_VERSION=1.11.0
ARG ATATUS_ENABLED=TRUE

ENV \
    # When using Composer, disable the warning about running commands as root/super user
    COMPOSER_ALLOW_SUPERUSER=1 \
    # Persistent runtime dependencies
    DEPS="php8 \
        php8-common \
        php8-curl \
        php8-dom \
        php8-exif \
	php8-fileinfo \
        php8-ftp \
        php8-gd \
        php8-iconv \
        php8-mysqli \
        php8-openssl \
        php8-pdo \
        php8-posix \
        php8-soap \
        php8-zip \
        php8-ldap \
        php8-bcmath \
        php8-calendar \
        php8-gettext \
        php8-pcntl \
        php8-phar \
	php8-simplexml \
        php8-sockets \
	php8-tokenizer \
        php8-xmlreader \
        php8-zip \
        php8-zlib \
        php8-xsl \
        php8-opcache \
        php8-ctype \
        php8-pdo_mysql \
        php8-pdo_sqlite \
        php8-sqlite3 \
        php8-intl \
        php8-fpm \
        php8-mysqli \
        curl \
        ca-certificates \
        supervisor \
        bash \
        tzdata \
        openssl \
        wget \
        curl \
        bash"

# Install deps
RUN apk add --no-cache \
	curl \
    ca-certificates \
    supervisor \
    bash \
    tzdata \
    openssl \
    wget \
    curl \
    bash \
    fcgi \
    nano \
    php8 \
    php8-common \
    php8-curl \
    php8-dom \
    php8-exif \
    php8-fileinfo \
    php8-ftp \
    php8-gd \
    php8-iconv \
    php8-mysqli \
    php8-openssl \
    php8-pdo \
    php8-posix \
    php8-soap \
    php8-session \
    php8-redis \
    php8-zip \
    php8-ldap \
    php8-bcmath \
    php8-calendar \
    php8-gettext \
    php8-pcntl \
    php8-phar \
    php8-simplexml \
    php8-sockets \
    php8-tokenizer \
    php8-xmlreader \
    php8-zip \
    php8-zlib \
    php8-xsl \
    php8-opcache \
    php8-ctype \
    php8-pdo_mysql \
    php8-pdo_sqlite \
    php8-sqlite3 \
    php8-intl \
    php8-fpm \
    php8-mysqli && \

	ln -snf /usr/bin/php8 /usr/bin/php && \
	ln -snf /usr/sbin/php-fpm8 /usr/sbin/php-fpm && \

	# Symlink current version
	mkdir /etc/php && \
	ln -snf /etc/php8 /etc/php/current;

# Composer
RUN EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)" && \
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")" && \
    if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; \
    then \
        >&2 echo 'ERROR: Invalid installer signature' \
        rm composer-setup.php \
    exit 1; \
    fi && \
    php composer-setup.php --quiet --install-dir=/usr/local/bin --filename=composer && \
    RESULT=$? && \
    rm composer-setup.php && \
    exit $RESULT

RUN if [ "$ATATUS_ENABLED" == "TRUE" ]; then \
	# Atatus
	wget https://s3.amazonaws.com/atatus-artifacts/atatus-php/downloads/atatus-php-$ATATUS_VERSION-x64-musl.tar.gz && tar -xzvf atatus-php-$ATATUS_VERSION-x64-musl.tar.gz && cd atatus-php-$ATATUS_VERSION-x64-musl && ./install.sh && rm -f /atatus-php-$ATATUS_VERSION-x64-musl.tar.gz && rm -rf /atatus-php-$ATATUS_VERSION-x64-musl && \
	sed -i -e 's#atatus.trace.response_time = 2000#atatus.trace.response_time = 1500#g' /etc/php/current/conf.d/atatus.ini && \
	  sed -i -e 's#atatus.collector.pidfile = "/var/run/atatus-php-collector.pid"#atatus.collector.pidfile = "/run/atatus-php-collector.pid"#g' /etc/php/current/conf.d/atatus.ini && \
	  sed -i -e 's#atatus.collector.connection = "/tmp/.atatus.sock"#atatus.collector.connection = "/run/atatus.sock"#g' /etc/php/current/conf.d/atatus.ini && \
	# Write log files to stdout
	rm -f /var/log/atatus/agent.log && rm -f /var/log/atatus/collector.log && rm -f /var/log/atatus/debug.txt && ln -sf /dev/null /var/log/atatus/agent.log && ln -sf /dev/null /var/log/atatus/collector.log && ln -sf /dev/null /var/log/atatus/debug.txt; \
	fi

# PHP Config
ADD /php/conf/php-fpm.conf /etc/php/current/php-fpm.conf
ADD /php/conf/php.ini /etc/php/current/php.ini
ADD /php/conf/php-www.conf /etc/php/current/php-fpm.d/www.conf

# Clear out garbage
RUN unset DEPS && rm -rf /run/php && rm -rf /run/php-fpm7.3

# Start script
ADD /php/scripts/start.sh /start.sh
RUN chmod +x /start.sh

# Start cron script
ADD /php/scripts/start-cron.sh /start-cron.sh
RUN chmod +x /start-cron.sh

# Start worker script
ADD /php/scripts/start-worker.sh /start-worker.sh
RUN chmod +x /start-worker.sh

# Configure script
ADD /php/scripts/configure.sh /configure.sh
RUN chmod +x /configure.sh

# Healthcheck script
ADD /php/scripts/healthcheck.sh /healthcheck.sh
RUN chmod +x /healthcheck.sh

CMD ["/start.sh"]
