FROM alpine:edge

ARG ATATUS_VERSION=1.14.0
ARG ATATUS_ENABLED=TRUE

ENV \
    # When using Composer, disable the warning about running commands as root/super user
    COMPOSER_ALLOW_SUPERUSER=1 \
    # Persistent runtime dependencies
    DEPS="php81 \
        php81-common \
        php81-curl \
        php81-dom \
        php81-exif \
        php81-fileinfo \
        php81-ftp \
        php81-gd \
        php81-iconv \
        php81-mysqli \
        php81-openssl \
        php81-pdo \
        php81-posix \
        php81-soap \
        php81-zip \
        php81-ldap \
        php81-bcmath \
        php81-calendar \
        php81-gettext \
        php81-mbstring \
        php81-pcntl \
        php81-phar \
        php81-simplexml \
        php81-sockets \
        php81-tokenizer \
        php81-xmlreader \
        php81-zip \
        php81-zlib \
        php81-xsl \
        php81-opcache \
        php81-ctype \
        php81-pdo_mysql \
        php81-pdo_sqlite \
        php81-sqlite3 \
        php81-intl \
        php81-fpm \
        php81-mysqli \
        php81-sodium \
        curl \
        ca-certificates \
        supervisor \
        bash \
        tzdata \
        openssl \
        wget \
        curl \
        bash"

# Install deps
RUN apk add --no-cache \
    curl \
    ca-certificates \
    supervisor \
    bash \
    tzdata \
    openssl \
    wget \
    curl \
    bash \
    fcgi \
    nano \
    tidyhtml \
    php81 \
    php81-pecl-apcu \
    php81-bz2 \
    php81-common \
    php81-curl \
    php81-dom \
    php81-exif \
    php81-fileinfo \
    php81-ftp \
    php81-gd \
    php81-iconv \
    php81-pecl-imagick \
    php81-mbstring \
    php81-mysqli \
    php81-openssl \
    php81-pdo \
    php81-posix \
    php81-soap \
    php81-session \
    php81-redis \
    php81-zip \
    php81-ldap \
    php81-bcmath \
    php81-calendar \
    php81-gettext \
    php81-pcntl \
    php81-phar \
    php81-simplexml \
    php81-shmop \
    php81-sysvmsg \
    php81-sysvsem \
    php81-sysvshm \
    php81-sockets \
    php81-tidy \
    php81-tokenizer \
    php81-xmlreader \
    php81-zip \
    php81-zlib \
    php81-xsl \
    php81-xml \
    php81-xmlwriter \
    php81-opcache \
    php81-ctype \
    php81-pdo_mysql \
    php81-pdo_sqlite \
    php81-sqlite3 \
    php81-intl \
    php81-fpm \
    php81-mysqli \
    php81-sodium && \

    ln -snf /usr/bin/php81 /usr/bin/php && \
    ln -snf /usr/sbin/php-fpm81 /usr/sbin/php-fpm && \

    # Symlink current version
    mkdir /etc/php && \
    ln -snf /etc/php81 /etc/php/current;

# Composer
RUN EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)" && \
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")" && \
    if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; \
    then \
        >&2 echo 'ERROR: Invalid installer signature' \
        rm composer-setup.php \
    exit 1; \
    fi && \
    php composer-setup.php --quiet --install-dir=/usr/local/bin --filename=composer && \
    RESULT=$? && \
    rm composer-setup.php && \
    exit $RESULT

RUN version=$(php -r "echo PHP_MAJOR_VERSION.PHP_MINOR_VERSION;") \
    && architecture=$(case $(uname -m) in i386 | i686 | x86) echo "i386" ;; x86_64 | amd64) echo "amd64" ;; aarch64 | arm64 | armv8) echo "arm64" ;; *) echo "amd64" ;; esac) \
    && curl -A "Docker" -o /tmp/blackfire-probe.tar.gz -D - -L -s https://blackfire.io/api/v1/releases/probe/php/alpine/$architecture/$version \
    && mkdir -p /tmp/blackfire \
    && tar zxpf /tmp/blackfire-probe.tar.gz -C /tmp/blackfire \
    && mv /tmp/blackfire/blackfire-*.so $(php -r "echo ini_get ('extension_dir');")/blackfire.so \
    && rm -rf /tmp/blackfire /tmp/blackfire-probe.tar.gz

RUN if [ "$ATATUS_ENABLED" == "TRUE" ]; then \
    # Atatus
    architecture=$(case $(uname -m) in i386 | i686 | x86) echo "i386" ;; x86_64 | amd64) echo "amd64" ;; aarch64 | arm64 | armv8) echo "arm64" ;; *) echo "x64" ;; esac) && \
    wget https://s3.amazonaws.com/atatus-artifacts/atatus-php/downloads/atatus-php-$ATATUS_VERSION-$architecture-musl.tar.gz && tar -xzvf atatus-php-$ATATUS_VERSION-$architecture-musl.tar.gz && cd atatus-php-$ATATUS_VERSION-$architecture-musl && ./install.sh && rm -f /atatus-php-$ATATUS_VERSION-$architecture-musl.tar.gz && rm -rf /atatus-php-$ATATUS_VERSION-$architecture-musl && \
    sed -i -e 's#atatus.trace.response_time = 2000#atatus.trace.response_time = 1500#g' /etc/php/current/conf.d/atatus.ini && \
    sed -i -e 's#atatus.collector.pidfile = "/var/run/atatus-php-collector.pid"#atatus.collector.pidfile = "/run/atatus-php-collector.pid"#g' /etc/php/current/conf.d/atatus.ini && \
    sed -i -e 's#atatus.collector.connection = "/tmp/.atatus.sock"#atatus.collector.connection = "/run/atatus.sock"#g' /etc/php/current/conf.d/atatus.ini && \
    # Write log files to stdout
    rm -f /var/log/atatus/agent.log && rm -f /var/log/atatus/collector.log && rm -f /var/log/atatus/debug.txt && ln -sf /dev/null /var/log/atatus/agent.log && ln -sf /dev/null /var/log/atatus/collector.log && ln -sf /dev/null /var/log/atatus/debug.txt; \
    fi

# PHP Config
ADD /php/conf/php-fpm.conf /etc/php/current/php-fpm.conf
ADD /php/conf/php.ini /etc/php/current/php.ini
ADD /php/conf/php-www.conf /etc/php/current/php-fpm.d/www.conf

# Clear out garbage
RUN unset DEPS && rm -rf /run/php && rm -rf /run/php-fpm8.1

# Start script
ADD /php/scripts/start.sh /start.sh
RUN chmod +x /start.sh

# Start cron script
ADD /php/scripts/start-cron.sh /start-cron.sh
RUN chmod +x /start-cron.sh

# Start worker script
ADD /php/scripts/start-worker.sh /start-worker.sh
RUN chmod +x /start-worker.sh

# Configure script
ADD /php/scripts/configure.sh /configure.sh
RUN chmod +x /configure.sh

# Healthcheck script
ADD /php/scripts/healthcheck.sh /healthcheck.sh
RUN chmod +x /healthcheck.sh

CMD ["/start.sh"]
